### ISSUE TITLE
Custom Texture

### ISSUE THREAD

**Issue by pakjuaan** [HenryOfCarim/albam_reloaded#11]
Hi, I was trying to add a new mesh with new texture on the chris normal model. However, I keep getting this error in blender. 
![error](https://user-images.githubusercontent.com/57705784/182082024-8c12dc63-5f50-4f07-b3ae-fa2c6e44933c.png)

I don't get any errors when adding a new mesh but it must use the existing material in the chris model
![re5dx9 2022-08-01 13-52-11](https://user-images.githubusercontent.com/57705784/182081849-865e461e-de47-41da-8d73-b0ec15702b12.png)
a22.png)

Any fixes for this?

**Comment by HenryOfCarim** [comment]
Hi, the way of adding new textures is kinda cumbersome, I believe this happened because you added a texture but didn't set a Fake user option for the texture container and it was removed by Blender after saving. Also what version of Albam do you use? I believe I added an error message that shows texture info in this case.
![image](https://user-images.githubusercontent.com/18252816/182169041-2d1eb110-ccac-4184-99ca-e0d5c849b279.png)
