### ISSUE TITLE
Glitchy material simplification 

### ISSUE THREAD

**Issue by HenryOfCarim** [HenryOfCarim/albam_reloaded#3]
It is very noticeable on static meshes because they have separated an alpha transparency map _AM and a lightmap _LM
![image](https://user-images.githubusercontent.com/18252816/179434635-e505f693-fbf3-4313-a18b-4be2ab5d395b.png)
![image](https://user-images.githubusercontent.com/18252816/179434661-b1fa8787-a9b1-4f76-bee9-4b2bcf612108.png)
In this case, 5 textures are transformed into 3

**Comment by Brachi** [comment]
A first step would be to manually create a shader that holds those missing textures and make it look good.
I think i simply didn't add them because I didn't know how to display them.

Alternatively, they could be loaded into the shader but only for exporting purposes, providing no output in the blender material.
